name: Build & Publish Release APK

on:
  push:
    tags:
      - 'main'

env:
  PROJECT_PATH: app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/gradle-build-action@v2
      - name: Build
        working-directory: ${{ env.PROJECT_PATH }}
        run: ./gradlew assemble
