name: Build & Publish Debug APK

on:
 push:
   branches:
     - main
   tags:
     - "v*"
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/gradle-build-action@v2
      - name: Build
        run: ./gradlew assemble
